name: WearWidget

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'WearWidget/**'
      - '.github/workflows/WearWidget.yml'
  pull_request:
    paths:
      - 'WearWidget/**'
      - '.github/workflows/WearWidget.yml'

env:
  SAMPLE_PATH: WearWidget

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6
        with:
          distribution: 'temurin'
          java-version: 25
          cache: gradle

      - name: Build and Verify Screenshots
        working-directory: ${{ env.SAMPLE_PATH }}
        run: ./gradlew check verifyRoborazziDebug --stacktrace
